import {useEffect,useRef,useState} from 'react';
import Splash from './Splash.jsx';
import {SCHOOL,IMG,pillars,academics,experiences,facilities,why,timeline,gallery} from './data.js';
function useReveal(){useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.15});document.querySelectorAll('.rv').forEach(el=>io.observe(el));return()=>io.disconnect()},[])}
const Pic=({src,emoji,cls='',alt=''})=>src?<img className={cls} src={src} loading="lazy" alt={alt}/>:<div className={'ph '+cls} aria-hidden>{emoji}</div>;
const Head=({tag,title,sub})=><div className="head rv"><span className="tag">{tag}</span><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>;
const links=['Home','About','Academics','Campus Life','Facilities','Admissions','Gallery','Achievements','Testimonials','Contact'];
const id=s=>s.toLowerCase().replace(' ','-');
function Header(){const[s,setS]=useState(false),[o,setO]=useState(false);
 useEffect(()=>{const f=()=>setS(scrollY>40);f();addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);
 return<header className={'hdr'+(s?' glass':'')}><a href="#home" className="brand"><img src={IMG.logo} alt={SCHOOL.name}/></a>
 <nav className={o?'open':''}>{links.map(l=><a key={l} href={'#'+id(l)} onClick={()=>setO(false)}>{l}</a>)}</nav>
 <div className="cta"><a href="#contact" className="btn ghost">Enquire Now</a><a href="#admissions" className="btn">Apply for Admission</a></div>
 <button className={'burger'+(o?' x':'')} aria-label="Menu" onClick={()=>setO(!o)}><i/><i/><i/></button></header>}
function Hero(){
 return<section id="home" className="hero"><div className="parts">{Array.from({length:18},(_,i)=><i key={i} style={{left:(i*37%100)+"%",animationDelay:(i*.7)+"s",animationDuration:(8+i%5*2)+"s",background:["#fbbf24","#38bdf8","#f472b6","#4ade80","#a78bfa"][i%5]}}/>)}</div><div className="blob b1"/><div className="blob b2"/>
 <div className="hero-txt"><span className="badge">✨ Welcome to Excellence in Education</span><h1>Where Young Minds <em>Learn, Grow</em> & Shine</h1>
 <p>Creating confident learners through academic excellence, creativity, character and holistic development.</p>
 <div className="row"><a href="#about" className="btn">Explore Our School</a><a href="#admissions" className="btn alt">Admissions Open</a></div><a className="tour" href="#facilities">Take a Virtual Tour →</a></div>
 <div className="hero-vis">{IMG.hero?<Pic src={IMG.hero} emoji="🏫" cls="hero-img" alt="Nalanda school campus"/>:<div className="orb"><div className="core">🏫</div>{["📚","🎨","🔬","🎵","⚽","🧮"].map((e,i)=><span key={i} className="sat" style={{"--a":i*60+"deg",animationDelay:"-"+i*2+"s"}}><em>{e}</em></span>)}</div>}<div className="fl f1">🎓 Create. Educate. Innovate.</div><div className="fl f2">📚 Since {SCHOOL.founded}</div><div className="fl f3">🌈 Play-way learning</div></div></section>}
const strip=[['🏆','Academic Excellence','Outstanding results'],['🌱','Holistic Development','Mind, body & values'],['👩‍🏫','Experienced Faculty','Caring & qualified'],['🖥️','Modern Infrastructure','Digital classrooms']];
function Strip(){return<section className="strip">{strip.map(([i,t,d],k)=><div key={t} className="card tilt rv" style={{'--d':k*.1+'s'}}><span className="ic">{i}</span><h4>{t}</h4><p>{d}</p></div>)}</section>}
function About(){const[m,setM]=useState(false);return<section id="about" className="sec about"><div className="imgs rv"><Pic src={IMG.about} emoji="🏫" cls="big" alt="Nalanda school sports campus"/><Pic src={IMG.about2} emoji="🧒" cls="small" alt="Students enjoying a creative art activity"/></div>
 <div className="rv"><span className="tag">About Our School</span><h2>Educating with heart since {SCHOOL.founded}</h2>
 <p>The {SCHOOL.society} was founded in {SCHOOL.founded} by {SCHOOL.founder} to serve society through education. Nalanda English Medium School is its next step, offering personalised attention, tech-infused teaching and a global outlook.{m&&' We follow the Educate international curriculum, as followed by Orchids International Schools, India, with a programme designed so children can face tomorrow\'s challenges boldly and confidently.'}</p>
 <ul className="facts"><li>📅 Established {SCHOOL.founded}</li><li>🏆 Academic Excellence</li><li>🌟 Student Development</li><li>👩‍🏫 Experienced Faculty</li></ul>
 <button className="btn" onClick={()=>setM(!m)}>{m?'Show Less':'Read More'} →</button></div></section>}
const Timeline=()=><section className="sec"><Head tag="Our Journey" title="Our Educational Journey"/><div className="tl">{timeline.map(([y,t,d],i)=><div key={t} className={'tli rv '+(i%2?'r':'')}><span className="dot"/><b>{y}</b><h4>{t}</h4><p>{d}</p></div>)}</div></section>;
const Pillars=()=><section className="sec tint"><Head tag="Four Pillars" title="Four Pillars of Success"/><div className="grid4">{pillars.map(([n,t,i,d,g])=><div key={n} className="pillar tilt rv" style={{background:`linear-gradient(135deg,${g})`}}><span className="num">{n}</span><span className="big-ic">{i}</span><h3>{t}</h3><p>{d}</p><span className="shape"/></div>)}</div></section>;
const Academics=()=><section id="academics" className="sec"><Head tag="Academics" title="A path for every stage"/><div className="grid3">{academics.map(([t,i,l,g])=><article key={t} className="acad tilt rv"><div className="ah" style={{background:`linear-gradient(135deg,${g})`}}>{i}</div><h3>{t}</h3><ul>{l.map(x=><li key={x}>{x}</li>)}</ul><a href="#admissions">Explore Academics →</a></article>)}</div></section>;
const Beyond=()=><section id="campus-life" className="sec tint"><Head tag="Life at Our School" title="Learning Beyond the Classroom" sub="Where every day becomes an opportunity to learn, explore and create."/><div className="grid4">{experiences.map(([t,i])=><div key={t} className="card exp tilt rv"><span className="ic spin">{i}</span><h4>{t}</h4></div>)}</div></section>;
function Facilities(){const[a,setA]=useState(null);useEffect(()=>{const k=e=>e.key==='Escape'&&setA(null);addEventListener('keydown',k);return()=>removeEventListener('keydown',k)},[]);
 return<section id="facilities" className="sec"><Head tag="Facilities" title="Spaces that inspire"/><div className="mason">{facilities.map(({name,src})=><button key={name} className="fac rv" onClick={()=>setA({name,src})} aria-label={`View ${name} photo`}><img className="fac-img" src={src} loading="lazy" alt={name}/><span className="fac-name">{name}</span></button>)}</div>
 {a&&<div className="modal" onClick={()=>setA(null)} role="dialog" aria-modal><div className="mbox" onClick={e=>e.stopPropagation()}><img src={a.src} alt={a.name} style={{maxWidth:'100%',maxHeight:'70vh',objectFit:'contain',borderRadius:16}}/><h3>{a.name}</h3><button className="btn" onClick={()=>setA(null)}>Close</button></div></div>}</section>}
const cats=['All','Academics','Sports','Events','Achievements','Campus','Activities'];
function Gallery(){const[c,setC]=useState('All'),[lb,setLb]=useState(null);const L=gallery.filter(g=>c==='All'||g.c===c);
 useEffect(()=>{const k=e=>e.key==='Escape'&&setLb(null);addEventListener('keydown',k);return()=>removeEventListener('keydown',k)},[]);
 return<section id="gallery" className="sec"><Head tag="Our Memories" title="Moments That Become Memories"/><div className="tabs rv">{cats.map(x=><button key={x} className={x===c?'on':''} onClick={()=>setC(x)}>{x}</button>)}</div>
 <div className="gal">{L.map((g,i)=><button key={g.t} className={'gi h'+g.h} style={{'--h':i*47%360}} onClick={()=>setLb(g)}>{g.src?<img src={g.src} loading="lazy" alt={g.t}/>:<span className="fe">{g.e}</span>}<span className="ov"><b>{g.t}</b><span className="ar">⤢</span></span></button>)}</div>
 {lb&&<div className="modal" onClick={()=>setLb(null)}><div className="mbox" onClick={e=>e.stopPropagation()}>{lb.src?<img src={lb.src} alt={lb.t} style={{maxWidth:'100%',maxHeight:'70vh',objectFit:'contain',borderRadius:16}}/>:<span className="fe">{lb.e}</span>}<h3>{lb.t}</h3><button className="btn" onClick={()=>setLb(null)}>Close</button></div></div>}</section>}
const Teachers=()=><section className="sec tint"><Head tag="Faculty" title="Meet Our Dedicated Educators" sub="Our caring, committed, qualified and dedicated teachers are our pillars of strength."/><div className="faculty-feature rv"><img src="/img/staff-team.png" loading="lazy" alt="Nalanda teachers together at a school event"/><div><span className="tag">Teaching with heart</span><h3>Learning, guided by care</h3><p>Our teachers teach children not just with their minds, but with their hearts—making learning enjoyable and rewarding while nurturing the importance of moral values.</p></div></div></section>;
const Why=()=><section className="sec tint"><Head tag="Why Choose Us" title="Why Parents Choose Us"/><div className="grid4">{why.map(([t,d])=><div key={t} className="card rv"><span className="chk">✓</span><h4>{t}</h4><p>{d}</p></div>)}</div></section>;
function Counter({to}){const[n,setN]=useState(0),r=useRef();useEffect(()=>{const io=new IntersectionObserver(([e])=>{if(!e.isIntersecting)return;io.disconnect();let s=null;const st=t=>{s??=t;const p=Math.min((t-s)/1400,1);setN(Math.round(to*p));p<1&&requestAnimationFrame(st)};requestAnimationFrame(st)});io.observe(r.current);return()=>io.disconnect()},[to]);return<b ref={r}>{n}+</b>}
const Ach=()=><section id="achievements" className="sec dark"><Head tag="Achievements" title="Celebrating Excellence"/><div className="stats rv"><div><Counter to={new Date().getFullYear()-SCHOOL.founded}/><span>Years of Service</span></div></div><div className="chips rv">{['Academic Results','Sports','Competitions','Cultural Activities','Scholarships'].map(x=><span key={x}>{x}</span>)}</div><p className="note">Add verified student/teacher counts in data.js to show more counters.</p></section>;
const MV=()=><section className="sec"><div className="grid2"><div className="mv m rv"><span className="big-ic">🚀</span><h3>Mission</h3><p>To provide a learning environment that inspires and motivates children and encourages them to explore limitless possibilities in their quest for knowledge.</p></div><div className="mv v glassc rv"><span className="big-ic">🔭</span><h3>Vision</h3><p>To equip every child with an academic programme suited to today's generation, so they can face tomorrow's challenges boldly, confidently and with strong moral values.</p></div></div></section>;
const Testi=()=><section id="testimonials" className="sec tint"><Head tag="Our Approach" title="What Parents Can Expect"/><div className="parent-promise rv"><span className="promise-mark" aria-hidden="true">♡</span><h3>Care that makes learning meaningful</h3><p>Our teachers bring care and dedication to every lesson, making learning enjoyable and rewarding while helping children develop strong moral values.</p><small>Based on the school's description of its teaching approach.</small></div></section>;
const Admit=()=><section id="admissions" className="cta-band"><h2>Give Your Child a Brighter Tomorrow</h2><p>Begin your child's journey towards knowledge, confidence and success.</p><div className="row"><a href="#contact" className="btn alt">Apply for Admission</a><a href="#contact" className="btn ghost light">Enquire Now</a></div></section>;
function Contact(){const[f,setF]=useState({}),[e,setE]=useState({}),[ok,setOk]=useState(false);
 const F=[['parent','Parent Name'],['phone','Phone Number','tel'],['email','Email','email'],['student','Student Name'],['cls','Class']];
 const sub=ev=>{ev.preventDefault();const er={};F.forEach(([k,l])=>{if(!f[k]?.trim())er[k]='Required'});if(f.phone&&!/^[+\d\s-]{10,15}$/.test(f.phone))er.phone='Enter a valid phone';if(f.email&&!/^\S+@\S+\.\S+$/.test(f.email))er.email='Enter a valid email';setE(er);if(!Object.keys(er).length){setOk(true);/* TODO: POST to your backend / email service */}};
 return<section id="contact" className="sec"><Head tag="Contact" title="Let's Start the Journey Together"/><div className="cgrid rv"><div className="cinfo">{[['📞','Phone',SCHOOL.phone],['✉️','Email',SCHOOL.email],['📍','Location',SCHOOL.address],['🕘','Office Hours',SCHOOL.hours]].map(([i,t,v])=><p key={t}><span>{i}</span><b>{t}</b><br/>{v||'Add in data.js'}</p>)}</div>
 {ok?<div className="form okmsg">🎉 Thank you! We'll contact you soon.</div>:<form className="form" onSubmit={sub} noValidate>{F.map(([k,l,t])=><label key={k}>{l}<input type={t||'text'} value={f[k]||''} onChange={ev=>setF({...f,[k]:ev.target.value})} aria-invalid={!!e[k]}/>{e[k]&&<em>{e[k]}</em>}</label>)}<label>Message<textarea rows="3" value={f.msg||''} onChange={ev=>setF({...f,msg:ev.target.value})}/></label><button className="btn">Send Enquiry</button></form>}</div>
 <div className="map rv">{SCHOOL.mapEmbedUrl?<iframe title="School location" src={SCHOOL.mapEmbedUrl} loading="lazy"/>:<p>📍 Paste your Google Maps embed URL in data.js</p>}</div></section>}
const socials=[['Facebook','https://www.facebook.com/people/Nalanda-Em-School-Offical/61558975125351/','f'],['Instagram','https://www.instagram.com/nalandaemschool_offical','◎'],['YouTube','https://www.youtube.com/channel/UCvMZdrP0Z78to0sFl438jqg','▶'],['WhatsApp','https://api.whatsapp.com/send?phone=919666376288','☎']];
const Footer=()=><footer><div className="fg"><div><img className="footer-logo" src={IMG.logo} alt={SCHOOL.name}/><p>Create. Educate. Innovate.</p></div><div><h5>Quick Links</h5>{['About','Academics','Facilities','Admissions','Gallery','Contact'].map(l=><a key={l} href={'#'+id(l)}>{l}</a>)}</div><div><h5>Useful Links</h5><a href="#">Privacy Policy</a><a href="#">Terms</a><a href="#">FAQ</a></div><div><h5>Contact</h5><p>{SCHOOL.phone}</p><p>{SCHOOL.email}</p><p>{SCHOOL.address}</p><h5 className="follow-title">Follow Us</h5><div className="soc">{socials.map(([name,url,icon])=><a key={name} className={'social-link social-'+name.toLowerCase()} href={url} target="_blank" rel="noopener noreferrer"><span className="social-mark" aria-hidden="true">{icon}</span><span>{name}</span></a>)}</div></div></div><p className="copy">© 2026 {SCHOOL.name}. All Rights Reserved.</p></footer>;
const words=['Create','Educate','Innovate','Play-Way Learning','Digital Classrooms','Abacus','Yoga','Smart Classrooms','Scholarships'];
const Marquee=()=><div className="mq"><div>{[...words,...words].map((w,i)=><span key={i}>✦ {w}</span>)}</div></div>;
function Progress(){const[p,setP]=useState(0);useEffect(()=>{const f=()=>setP(scrollY/(document.body.scrollHeight-innerHeight)*100);addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);return<div className="prog" style={{width:p+'%'}}/>}
export default function App(){const[sp,setSp]=useState(()=>!sessionStorage.getItem('seen'));const done=()=>{sessionStorage.setItem('seen','1');setSp(false)};useEffect(()=>{!sp&&setTimeout(()=>dispatchEvent(new Event('scroll')),50)},[sp]);useReveal();return<>{sp&&<Splash onDone={done}/>}<Progress/><Header/><main><Hero/><Marquee/><Strip/><About/><Timeline/><Pillars/><Academics/><Beyond/><Facilities/><Why/><Teachers/><Gallery/><Ach/><MV/><Testi/><Admit/><Contact/></main><Footer/></>}
